
name: Service Template - Python

networks:
  stack-network:
    driver: bridge

include:
  - .containers/docker-compose.observability.yaml
  - .containers/database/postgres/docker-compose.yaml
  - .containers/cache/redis/docker-compose.yaml

services:
  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - progress=plain
      ssh:
        - default
      target: runtime
    networks:
      - stack-network
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    environment:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    env_file:
      - .env.sample
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UVICORN_PORT}/healthcheck/dependencies"]
      interval: 3s
      timeout: 5s
      retries: 5
