[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
requires-poetry = ">=2.0"
package-mode = false

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.9.0"

# [[tool.poetry.source]]
# name = "private"
# url = "https://github.com/LuizFerraresi/toolbox"

[project.urls]
repository = "https://github.com/LuizFerraresi/service-template-python"

[project]
name = "service-template-python"
version = "0.1.0"
requires-python = ">=3.12.3,<4.0.0"
readme =  {file = "README.txt", content-type = "text/markdown"}
license-files = [
    "LICENSE"
]

dependencies = [
    "uvicorn[standard]==0.38.0",
    "dependency-injector==4.48.2",
    "fastapi==0.119.0",
    "pydantic==2.12.3",
    "pydantic-settings==2.11.0",
    "prometheus-client (>=0.23.1,<0.24.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
]

[dependency-groups]
development = [
    "pytest==8.3.4",
    "pytest-asyncio>=0.23.5",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.12.0",
    "respx==0.22.0",
    "ruff==0.12.7",
    "pre_commit==4.2.0",
    "pyright==1.1.404",
    "bandit==1.8.6"
]

[tool.bandit]
targets = ['src']
exclude_dirs = ['.venv', 'tests']

[tool.ruff]
line-length = 120
lint.select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
    "ANN", # annotations
    "S",   # bandit
    "D",   # pydocstyle

]
lint.ignore = ["B008", "D100"]          # flake8-bugbear: do not use bare except
lint.extend-safe-fixes = ["SIM", "I"]   # flake8-simplify and isort
lint.pydocstyle.convention = "google"
format.quote-style = "single"
format.indent-style = "space"
format.docstring-code-format = true
format.docstring-code-line-length = 60

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",  # Ignore assert statements in test files
    "D104",
    "ANN001",
    "ANN201"
]
"tests/data/*.py" = [
    "E501"
]

[tool.pyright]
exclude = [
    "**/__pycache__"
]
include = [
    "src"
]
pythonPlatform = "Linux"
venv = ".venv"
venvPath = "."
