[project]
name = "service-template-python"
version = "0.1.0"
requires-python = ">= 3.12"

dependencies = [

]

[project.optional-dependencies]
development = [
    "pytest==8.3.4",
    "pytest-asyncio>=0.23.5",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.12.0",
    "respx==0.22.0",
    "ruff==0.12.7",
    "pre_commit==4.2.0",
    "pyright==1.1.404",
    "bandit==1.8.6"
] 

[tool.bandit]
targets = ['src']
exclude_dirs = ['.venv', 'tests']

[tool.ruff]
line-length = 120
lint.select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
    "ANN", # annotations
    "S",   # bandit
    "D",   # pydocstyle

]
lint.ignore = ["B008", "D100"]          # flake8-bugbear: do not use bare except
lint.extend-safe-fixes = ["SIM", "I"]   # flake8-simplify and isort
lint.pydocstyle.convention = "google"
format.quote-style = "single"
format.indent-style = "space"
format.docstring-code-format = true
format.docstring-code-line-length = 60

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",  # Ignore assert statements in test files
    "D104",
    "ANN001",
    "ANN201"
]
"tests/data/*.py" = [
    "E501"
]

[tool.pyright]
exclude = [
    "**/__pycache__"
]
include = [
    "src"
]
pythonPlatform = "Linux"
venv = ".venv"
venvPath = "."
