# Example Redis Insights config

# Set default HTTP port
server.port=8001

# Enable telemetry (optional)
telemetry.enabled=true

# Path to store database connections & settings
database.path=/db

# Logging
logging.level=INFO
